// https://projecteuler.net/problem=2

/* 
Question 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

let result002: number[] = [1, 2];
let ltn: number[] = [1, 2];
let a: number, b: number, c: number;

function evenFibonacciNumbers() {
  a = ltn[0];
  b = ltn[1];

  while (ltn[1] <= 10 ** 6 * 4) {
    c = a + b;
    if (c > 10 ** 6 * 4) break;
    a = b;
    b = c;
    ltn[0] = a;
    ltn[1] = b;
    result002.push(b);
  }

  console.log(result002);
}

evenFibonacciNumbers();
